### ISSUE TITLE
Due Dates

### ISSUE THREAD

**Issue by cseitz** [cseitz/SoftwareEngineering-Team-TGMGPA#10]

**Comment by cseitz** [comment]
How am I supposed to make a duedate thingy on here? any ideas or suggestions?

**Comment by cseitz** [comment]
Relevant Issue: #59

**Comment by wesley-ka** [comment]
Along with adding the support for it in backend, I think we should do something in the frontend, maybe a collapsible tab in the sides or bottom to put the "upcoming tasks" that are due after today or tomorrow, and like mentioned in #59, the tasks due today and tomorrow get automatically put on the center view.

**Comment by justintclark** [comment]
How is this going to work? Are we going to have a clock that is tied to whatever clock is in the database, and then compare the dates listed in the task to the date in the database to confirm if task.date == today.date?"
If so, should/could we add a clock to the banner, next to the weather, or would that result in too much clutter? If so, possibly elsewhere on the screen? It's not necessary, but it might help.

**Comment by cseitz** [comment]
We need a new string value on Tasks (both frontend and backend) that is used to store a time. We should use [DateTime-Local Input](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local) to have users select a datetime.

This time is locally set based on their timezone, as will all datetime operations we do. We don't need an internal database clock. If your client sided datetime is within 24 hours of the due date of an task, it is considered "today" and would automatically be moved to the today column.

@justintclark @wesaka

**Comment by cseitz** [comment]
Also, please do this on a separate branch.

**Comment by wesley-ka** [comment]
I had thought of almost exactly what @cseitz said, the only addition that I think could work is to manually set a timezone if desired (if not specified, just get the internal timezone). I had thought about setting the values for the task to be in UTC and adding an extra field to store the timezone, something like [Moment Timezone library](https://momentjs.com/timezone/) makes it very simple to do that, also doing the conversions wouldn't be too much of a hassle. This is something I personally really miss from calendars, as most of the things I have to do and turn in are due -05:00GMT and I'm on -03:00GMT.

But for the sake of simplicity, I'm building the version where only the local time is used, the extra timezone could be a separate issue for that matter.

**Comment by cseitz** [comment]
Actually, convert the times to GMT or specify the time zone in the date string. 

Whatever implementation you use probably already specifies the time zone in the string. If that is the case, JavaScript date operations will automatically handle everything for us so you don't need to consider timezones.

Feel free to include moment.js if you feel it would be useful.

@wesaka

**Comment by wesley-ka** [comment]
Added the dates when creating and modifying a task, still have ways to go, as I need to specify how changing dates will changes tasks and whatnot.

Actually found it better to add moment.js but not for parsing dates, it helps a lot when changing dates and handling them overall. As when handling with pure javascript, it would mess up the timezones (javascript automatically gets your local timezone, html5 date input does not), when testing here, every operation I did with dates would get 3 hours wrong, implementing moment solved that automatically.

**Comment by cseitz** [comment]
I pushed some changes that save dates as an ISOString (aka `YYYY-MM-DDTHH:mm:ss.sss`) as well as converting that to local time and setting the `datetime-local` input's value to the correct datetime.

Apparently `datetime-local` is weird and simply setting its value via HTML does not properly apply. Instead, the value is now parsed and set inside of the `modal_shown` callback on Tasks.

I have also made a getter for Task.date which will return false if the date is empty. This means we can use `task.date` in logic for determining if a task has a due date or not, and the date is returned if it has one.

Be sure to fetch and pull my changes before continuing to work on this feature.

@wesaka

**Comment by cseitz** [comment]
Is there anything else that needs to be done for this feature?

**Comment by wesley-ka** [comment]
I fixed a bug where the date wouldn't display on the HTML field, as it expects a date without the timezone offset, and correctly parsing the date with timezone offset to save on the database. All of that is done with moment, as it has settings for parsing from HTML5 input format and setting to ISO format when saving to the database.

One thing that I spent a lot of time trying to figure out, was how we are going to change the dates from "tomorrow" to today, but ultimately used the tasklist component to do so, checking every task prior to displaying it if the task is on the "right" column. A new behavior that I noticed with this, is that the user can't create a task on the "tomorrow" column with today's date, in my head it makes sense, but I don't know if this is really a feature or a bug.

I will create an "upcoming tasks" issue to deal with those tasks, and maybe we could work on that this next sprint.

**Comment by cseitz** [comment]
That Should be fine.

Perhaps when you move a task that is due today to tomorrow, it increments the due date by 1 day?

**Comment by wesley-ka** [comment]
Nice catch. It increments the date but doesn't change columns, as it all happens in the wrong order. Will fix.

**Comment by wesley-ka** [comment]
Fixed. Just a matter of swapping the order of setting dates and columns.

**Comment by cseitz** [comment]
Is this ready to review yet? If possible, I'd like to get this issue done before lunch so I can incorporate it into our sprint presentation.

**Comment by wesley-ka** [comment]
Oh sorry, forgot to move to review.

**Comment by cseitz** [comment]
I made some small adjustments to the code.

I updated the server-side validation for the date field to be 25 characters so the timezone is included. I also removed the default due date of 1/1/2021 in setup.py.

I just tested now and everything works nicely.
