### ISSUE TITLE
improve the edit window

### ISSUE THREAD

**Issue by nbaker24** [cseitz/SoftwareEngineering-Team-TGMGPA#101]
try to make the edit window more user friendly/visually appealing.

**Comment by cseitz** [comment]
Needs more details. Will update soon.

**Comment by jkeegan1** [comment]
so i was looking at the edit window in dark mode and the box is white when you click on it. The only thing that changes is the text being highlighted black. Should we make the box itself darker so its more visually pleasing? Also i think we should add a box around the edit button itself to give it a more 2D feel. Maybe in the future add boxes to everything like the move to tomorrow/today and delete buttons. It could give the taskbook a better appearance since its pretty 1D right now. any feedback?

**Comment by nbaker24** [comment]
mostly what this was referring to was the description box for the task being very small and smashed into the same line as the date. making it so if you had a description more than a few words long you wouldn't be able to see the whole thing while writing it. also if you make a due date for the task and go in to edit the due date the time that it is due, even if you don't put one, is in the same line. This could be fixed by either removing the time from the due date or adding a time category for the edit box. I do however like the idea of adding things to the website that makes it feel more visually appealing in regard to the buttons and pop up boxes.

**Comment by jkeegan1** [comment]
![image](https://user-images.githubusercontent.com/75549473/112067509-8b864d80-8b3e-11eb-8821-db4d1e15e6ca.png)
@cseitz 
implemented separation of date and time and also implemented description textarea expansion

**Comment by cseitz** [comment]
Looks like some good progress. 

We should put the description box on a new line and remove the `description: ` portion. Make the description be the full width of the box, just like input box right above it.

We'll make some more adjustments to the other fields too, but focus on this first.

**Comment by jkeegan1** [comment]
![image](https://user-images.githubusercontent.com/75549473/112240088-0a9e8300-8c1e-11eb-91fb-364648996ae2.png)

@cseitz 
fixed the textarea color and moved the box to the next line.  Did you actually want me to remove ```Description: ``` or did you want me to remove the text inside?

**Comment by cseitz** [comment]
Put "Add Details" as placeholder text for the description.

Convert the description field to a `textarea` element.

**Comment by rsilvey1** [comment]
Newest version of the edit window with the textarea added
![image](https://user-images.githubusercontent.com/38113144/113228502-05b38200-9263-11eb-8a97-4c4bb5d27035.png)

**Comment by cseitz** [comment]
Change "Add a Task" to an input element (not textarea).

Remove unnecessary newline between "Add a task" and "Add details".

`text-align: center;` the create button.

**Comment by cseitz** [comment]
![image](https://user-images.githubusercontent.com/54898870/113633221-89da8080-963a-11eb-92d6-955d2eaebdfa.png)

**Comment by cseitz** [comment]
#114 Included in this. @cseitz will be implementing new calendar date-picker via bootstrap.
