### ISSUE TITLE
Task Due Dates

### ISSUE THREAD

**Issue by cseitz** [cseitz/SoftwareEngineering-Team-TGMGPA#110]

**Comment by Chulz25** [comment]
The structure of due dates is gonna like this for selenium
Steps
1. Find edit task button
Or 
1. Create new task
2. Find due date input and ask user for due date
3. THe format will be Month --> TAB --> Day --> TAB -- > Year -->
4. AFter this the user will be asked if they want to assign a time to the due date or not with an If statement
5. Then click the save button or create button if creating the task.

**Comment by Chulz25** [comment]
The only reason we have to use TAB in the format is that the way the input is set up for the web application 
we cant just type it all in one line when the user is asked for the due date.

**Comment by Chulz25** [comment]
Code will be up by tomorrow dinner

**Comment by Chulz25** [comment]
code is pushed 
and tested @cseitz 
Just run it and make sure the dates work and time gets applied correctly to your firefox browser
Make sure you use the correct formate listed in the terminal on each step if needed

**Comment by cseitz** [comment]
Code looks good, but we'll be adjusting how due dates are selected due to #114 

For now, this issue is finished. I'll make another one to modify test code for the new datetime selector once that is implemented.
