### ISSUE TITLE
Descriptions for Tasks

### ISSUE THREAD

**Issue by cseitz** [cseitz/SoftwareEngineering-Team-TGMGPA#20]
Descriptions have already beeen implemented in the code for Tasks and the backend API, but we have no way to edit the description of tasks.

Add a new `textarea` HTML element to the edit task modal window so that we can edit the descriptions of tasks.

**Comment by cseitz** [comment]
Descriptions have been implemented but we don't have a way to edit them.

Someone should edit the task modal (located in `components/task.html`) and provide a way to edit `task.description`

**Comment by cseitz** [comment]
@justintclark Updated the description of this with more instructions for you.

**Comment by justintclark** [comment]
> @justintclark Updated the description of this with more instructions for you.

Thanks! I actually was messing around with it and made the description editable already, but it somehow broke the changing of the name, so I'm trying to figure out why that happened.

**Comment by justintclark** [comment]
Done. I uploaded it to the "Description" branch. Make sure it works for you. Thank you.

**Comment by cseitz** [comment]
Looks good. Merged into main.
