### ISSUE TITLE
Clickable Links in Task Descriptions

### ISSUE THREAD

**Issue by cseitz** [cseitz/SoftwareEngineering-Team-TGMGPA#21]
Descriptions are already implemented in markdown, which supports this feature.

This feature is being closed, but not moved to done because there is currently no way to edit descriptions.

Refer to #20

**Comment by cseitz** [comment]
Descriptions are already implemented in markdown, which supports this feature.

This feature is being closed, but not moved to done because there is currently no way to edit descriptions.

Refer to #20

**Comment by justintclark** [comment]
Should this issue be moved to done now that description editing is done?

**Comment by cseitz** [comment]
Yep! Thanks for reminding me!
