### ISSUE TITLE
Hover Transitions

### ISSUE THREAD

**Issue by cseitz** [cseitz/SoftwareEngineering-Team-TGMGPA#28]
Provides User Feedback to what is being interacted with on the website.

**Comment by Chulz25** [comment]
Looking into this at the very moment, it doesn't seem too bad. We have to implement a new CSS file named Transitions.css  to the public css folder. I'm trying to figure out how to connect already known entities like the trashcan and pencil icons.

**Comment by Chulz25** [comment]
For the transitions for word text we can use a simple css function

<style>
    transition: .5s
</style>
the speed can be adjusted but .5 seconds to 1 second is pretty responsive.

**Comment by Chulz25** [comment]
For the hover function me and chris used .hover for each of the task functions, 
$('.delete_task').hover(function() {
    this.innerHTML = "delete_forever"
}, function() {
    this.innerHTML = "delete"
this is using the icon site that we already have access to.
Site:
https://material.io/resources/icons/?style=baseline

**Comment by Chulz25** [comment]
Testing these changes now

**Comment by Chulz25** [comment]
Test went smoothly completed!

**Comment by cseitz** [comment]
Code looks good. I'm closing this issue and moving it to done.
