### ISSUE TITLE
Dark Mode Switch

### ISSUE THREAD

**Issue by cseitz** [cseitz/SoftwareEngineering-Team-TGMGPA#30]
Toggle Dark mode via a button. 

Put on top right of navigation bar.

Use the following starter code:
```js
window.darkmode = {
   enabled: false,
   toggle() {
      this.enabled = !this.enabled;
   },
   set(value) {
      this.enabled = value;
   }
}
```

Button should detect `window.darkmode.enabled` and start in either the on or off state depending on what it is. Clicking the button should run `window.darkmode.toggle()` and then update the button to reflect `window.darkmode.enabled`

Comment if you have any questions.

**Comment by cseitz** [comment]
#29 has been implemented. **DO NOT PASTE IN THE CODE ABOVE, BUT THE REFERENCES STILL WORK**

```js
window.darkmode.toggle()
console.log(window.darkmode.enabled ? 'is in dark mode' : 'is in light mode')
```

**Comment by wesley-ka** [comment]
Added the button for toggling dark mode. Please check if it is how it should be.

**Comment by cseitz** [comment]
Looks good. Moving to done.
