### ISSUE TITLE
Done and Done-All button

### ISSUE THREAD

**Issue by cseitz** [cseitz/SoftwareEngineering-Team-TGMGPA#52]
We should put this and the icon next to it to use. It looks great.

https://material.io/resources/icons/?icon=done&style=baseline

**Comment by wesley-ka** [comment]
How this should work? Clicking on the "done" button and applying the strikethrough effect and "done all" and applying it to all tasks?
Or more of a visual signaling thing that indicates that a task was done, along with the strikethrough?

**Comment by cseitz** [comment]
Currently just clicking the task marks it done or undone.

We would add a new button explicitly for marking something done or undone, and a check-all button at the top of the table.

Clicking the task would probably go into edit mode instead.

**Comment by cseitz** [comment]
This card has been moved to to-do for the sprint presentation, as it is considered part of the next sprint.

It will be placed within in-progress once the next sprint board is created.

**Comment by wesley-ka** [comment]
I just left the "clicking the task to mark it as done" behavior, if this is something that must go with the new done and done all buttons, please let me know and I fix it, as it is a really really quick fix.
