### ISSUE TITLE
Task color bug

### ISSUE THREAD

**Issue by NolSpencer** [cseitz/SoftwareEngineering-Team-TGMGPA#58]
When in light mode you cannot see the picker for task color, maybe we add an outline for light mode?

**Comment by cseitz** [comment]
Yes this is a bug. We should either add an outline or make the button appear even when not hovered; but probably the just the outline.

**Comment by NolSpencer** [comment]
maybe we can just make the starting color black instead of white for light mode?

**Comment by wesley-ka** [comment]
Added the outline. It is very thin and discrete but makes a huge difference

**Comment by cseitz** [comment]
Looks good. Closing and moving to done.

**Comment by cseitz** [comment]
> maybe we can just make the starting color black instead of white for light mode?

Not a good idea. We should make the color dependent on how your interface looks. That would lead to some weird behavior.
