### ISSUE TITLE
Login and Signup Page

### ISSUE THREAD

**Issue by cseitz** [cseitz/SoftwareEngineering-Team-TGMGPA#65]
Login with:
Github
Discord
Google

**NO USERNAME AND PASSWORD LOGINS, ONLY OAUTH**

**Comment by rsilvey1** [comment]
@cseitz sorry it took so long to get back to work on this, I've just been really busy at the moment. I'm in the process of adding the buttons, but it's not registering the path to the images. I've attached a screenshot of the login page and my code showing the image path that it isn't taking. Got any suggestions? Also, I do plan on making the other buttons look better, I just wanted to get at least one working before I move on to the others.
![image](https://user-images.githubusercontent.com/38113144/111081529-29906d00-84da-11eb-9d23-c8febf1da736.png)
![image](https://user-images.githubusercontent.com/38113144/111081560-4af15900-84da-11eb-9e06-40170a1c51e3.png)

**Comment by cseitz** [comment]
Converted to USERPASS only.
