### ISSUE TITLE
Email-Associated Database Entries

### ISSUE THREAD

**Issue by cseitz** [cseitz/SoftwareEngineering-Team-TGMGPA#67]
To prepare for the implementation of user accounts, we must make it so database Entries are tied to an email.

Fetching tasks should filter by email, as with updating, creating, etc.

For now, use a placeholder email of `shared@example.com` which will be replaced by a logged-in user's email once we add user account functionality.

**Comment by cseitz** [comment]
How is progress on this?

**Comment by Chulz25** [comment]
almost completed we just need to include the delete tasks() to the function then it will be done and ready for further testing.

**Comment by Chulz25** [comment]
almost finished need to modify delete tasks

**Comment by jkeegan1** [comment]
should be done by today

**Comment by jkeegan1** [comment]
what are you looking for in the delete_task() function?

**Comment by cseitz** [comment]
Same as the others. It needs to only delete ones where the email is the right email.

**Comment by jkeegan1** [comment]
how would one go about testing from this branch?

**Comment by cseitz** [comment]
Make sure you commit and push your changes.

I'm looking at the code right now and there is no way you are ready for any testing; you haven't done everything that needs to be done yet.

But to answer your question, my recommendation would be to add a query parameter that is an email, and then one would use that parameter in the frontend and that would change who the backend thinks is logged in. You would then test with 2 different emails with creating, editing, and deleting tasks and make sure that both emails have have completely separate task entries and don't influence eachother.

**Comment by cseitz** [comment]
There are still lots of problems with this code. I'll work with you guys after class to get it sorted.

**Comment by jkeegan1** [comment]
Thank you , I’d appreciate that
