### ISSUE TITLE
Coloring Tasks

### ISSUE THREAD

**Issue by cseitz** [cseitz/SoftwareEngineering-Team-TGMGPA#7]

**Comment by wesley-ka** [comment]
I added the functionality to change the color of the tasks, it is pretty basic but works, of course, needs a little improvement.

Took me longer than I would like to admit, but after figuring out what Dr. DeLozier did to get this thing working, and a bit of tidying up the code, everything worked out nicely.

**Comment by cseitz** [comment]
I'll review this code tomorrow and if it is all good, move this feature into the Done category.

**Comment by cseitz** [comment]
Nicely done @wesaka! Feature reviewed and put in the Done column!

👍
