### ISSUE TITLE
IP City Detection fails on HTTPS

### ISSUE THREAD

**Issue by cseitz** [cseitz/SoftwareEngineering-Team-TGMGPA#73]
The free subscription plan for the API does not allow us to use HTTPS, which is always going to be used when not on localhost.

We must use another API instead.

I recommend using Google's. Check out [this StackOverflow post](https://stackoverflow.com/a/53112761).

**Comment by NolSpencer** [comment]
I am having trouble of figuring out how to put things into variables to use for the second api (weather)... I also run into a console error when I test the code that was in weather2 branch. I don't know the exact error but it has something to do with google.maps.geocoder() line. Which is line 18 in the weather.js file.

**Comment by cseitz** [comment]
Looks good, merging in.
