### ISSUE TITLE
Due Dates Appearing next to Card Titles

### ISSUE THREAD

**Issue by cseitz** [cseitz/SoftwareEngineering-Team-TGMGPA#81]
Add a new field next to cards that displays their due date, if one exists.

If you have any questions, write a comment on this issue and I'll help you out.

**Comment by cpfeifer** [comment]
I keep going through all these files and feel lost in a sea of code, do you know if there is a specific variable or something storing the date to pull from? or even which files deal with this issue at all?

**Comment by cseitz** [comment]
You can find what you need inside `components/task.html`

This is how data is stored within each task.
```js
{
  id: false,
  day: 'today',
  name: '',
  description: '',
  completed: false,
  color: '#ffffff',
  date: '' // Should be in the 'YYYY-MM-DDTHH:mm:ssZ' format (moment provides this format by default)
}
```

All of these can be accessed in the HTML of a task via `{{ variableName }}`.

You can declare new variables within `render(HTML)`. You will need to do this in order to convert the stored date format into human-readable.
```js
{
  // ...
  formattedDate: this.data.date.length > 0 ? moment(this.data.date).calendar() : '',
  // ...
}
```

In the HTML of the task, you can do `{{ formattedDate }}` to insert the formatted date string.

Hope this helps. Let me know if you have any other questions @cpfeifer

**Comment by cpfeifer** [comment]
@cseitz thoughts?
![date](https://user-images.githubusercontent.com/20586077/113948760-a6fa8500-97db-11eb-8eb1-200dd9584502.PNG)

**Comment by cseitz** [comment]
yea we gotta make that text smaller and it needs to be pushed to the right

its hard to identify what the dates correspond to

**Comment by cpfeifer** [comment]
![updated](https://user-images.githubusercontent.com/20586077/115801221-38582280-a3aa-11eb-977c-9f9cff7ba1b1.PNG)

**Comment by cseitz** [comment]
That looks good. Put it in review and open a pull request.
