### ISSUE TITLE
Testing Framework for Frontend Code

### ISSUE THREAD

**Issue by cseitz** [cseitz/SoftwareEngineering-Team-TGMGPA#82]

**Comment by Chulz25** [comment]
Note for the driver to find the element, it has to find it by XPath not name because name doesn't work XPath works perfectly fine!

Example:
elem = driver.find_element_by_xpath("/html/body/div[1]/span[1]/b")

**Comment by Chulz25** [comment]
To find the xpath you have to inspect the website then highlight which element you want to find.
Right click and click copy xpath!
