### ISSUE TITLE
Test Task Class

### ISSUE THREAD

**Issue by cseitz** [cseitz/SoftwareEngineering-Team-TGMGPA#84]

**Comment by Chulz25** [comment]
With help from jeremy we have full tested the today column for creating new tasks 

Commit has been pushed moving this to review column!

**Comment by Chulz25** [comment]
@cseitz 
Moved to review for further testing

**Comment by Chulz25** [comment]
Note for testing
1.Make sure class is selected properly, i tested it on my pc also my mac works fine.
2. Make sure each task saves even though it is done through automation while using the firefox webdriver.

**Comment by cseitz** [comment]
Looks like a good start. Going to add more issues that involve more deeper testing of the task class.
