### ISSUE TITLE
Navigation Tabs underneath Banner

### ISSUE THREAD

**Issue by cseitz** [cseitz/SoftwareEngineering-Team-TGMGPA#87]
<img src="https://cdn.discordapp.com/attachments/805965540576460844/814313528004575262/unknown.png">

**Comment by cseitz** [comment]
Routes we need, in order:
- Taskbook
- About
- Settings
- Login

**Comment by wesley-ka** [comment]
Buttons for navigation operational.

Code is under "navigation" branch.

**Comment by cseitz** [comment]
Can you set up a pull request?
