### ISSUE TITLE
Undo Delete Task

### ISSUE THREAD

**Issue by cseitz** [cseitz/SoftwareEngineering-Team-TGMGPA#95]
When a task is deleted, a button should appear for like 10 seconds that says "Undo Delete" or something.

In order to undo the deletion, one must run
```js
Archives.undoDelete();
```

**Comment by cseitz** [comment]
Make it similar to Google Calendar
![image](https://user-images.githubusercontent.com/54898870/111228261-4603d680-85ba-11eb-9ad3-3c39ea589ea0.png)

**Comment by justintclark** [comment]
I'm finally home from travelling with family, so I can start focusing on this again. Sorry for the delay.

What is it exactly that I need to do with this? I believe you said all of the back end is done already, yeah? So, then all that's necessary is to do the front end (HTML)? 

I was looking into how Google Calendar implements this, but it is very difficult to get a glimpse at the code as it only seems to appear in the browser console for a split second and then disappears. Do we have a similar support for a popup window at the bottom of the screen, or does that need to be implemented?

**Comment by cseitz** [comment]
You can create a popup by using `position: absolute`. Pretty simple to implement.

Try it out, see if you can figure it out through googling. If you can't figure it out, I'll help some more.

**Comment by justintclark** [comment]
Ok, I put a branch up for undo delete. This has a very, very rudimentary version of an undo delete button. It performs the function of undoing the deletion of a task flawlessly (or so it seems). 

However, it's just a static button. How do I improve this? How do I make it appear only after a task is deleted and how do I set it on a timer to disappear after x number of seconds? 


Edit: I also noticed that undoing the deletion and refreshing deletes the item again.

**Comment by justintclark** [comment]
![image](https://user-images.githubusercontent.com/55370053/113635421-98c33200-963e-11eb-8352-0852403f759d.png)

Increased the padding. If you want more, let me know if you want more around the edges of the text, or in between the texts.

**Comment by cseitz** [comment]
Looks good. If everything works, set up a pull request and put this in review.
